apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
  labels:
    app: app-docker
spec:
  type: NodePort
  selector:
    app: app-docker
  ports:
  - name: appport 
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
